### ISSUE TITLE
Bug: mdbook cannot be published and resulted 404 at GitHub Pages

### ISSUE THREAD

**Issue by iandyh** [peaceiris/actions-mdbook#305]
**Describe the bug**
I was following the guides at the docs, including doing a dummy first release, but has no effect. 

Settings of my repo GitHub pages:

![Screen Shot 2020-08-26 at 9 13 11](https://user-images.githubusercontent.com/431658/91240309-9fbac580-e77c-11ea-99d3-03f20645d13f.png)

My action config yaml:

```

name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          #mdbook-version: 
          mdbook-version: 'latest'

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
```

**To Reproduce**
Follow the docs

**Expected behavior**
mdbook can be pushed from the `book` directory and rendered at GitHub pages

**Screenshots**
Please see above

**Your YAML file**
book repo: https://github.com/iandyh/shibuya-book

**Additional context**
