### ISSUE TITLE
Bug: Couldn't open SUMMARY.md

### ISSUE THREAD

**Issue by NuroDev** [peaceiris/actions-mdbook#36]
**Describe the bug**
Explicitly setting mdbook build path and instead resulting in the following error:
```
[ERROR] (mdbook::utils): Error: Couldn't open SUMMARY.md
[ERROR] (mdbook::utils): 	Caused By: No such file or directory (os error 2)
```

**To Reproduce**
Simply running the GitHub workflow

**Expected behavior**
mdbook build to run and complete.

**Screenshots**

**Your YAML file**
[nurodev/atlas/blob/master/.github/workflows/book.yml](https://github.com/NuroDev/atlas/blob/master/.github/workflows/book.yml)

**Additional context**
I have also done a sanity check and logged the current working directory when the step is run and it clearly shows that the book contents is present and ready to be build:
```
/home/runner/work/atlas/atlas/book
book.toml
custom.css
now.json
src
2020-01-08 16:54:46 [ERROR] (mdbook::utils): Error: Couldn't open SUMMARY.md
2020-01-08 16:54:46 [ERROR] (mdbook::utils): 	Caused By: No such file or directory (os error 2)
##[error]Process completed with exit code 101.
```

**Comment by peaceiris** [comment]
I am testing at https://github.com/peaceiris/test-NuroDev-atlas

It has failed with the same error, but https://github.com/peaceiris/test-mdbook have passed.
[log](https://github.com/peaceiris/test-mdbook/commit/699b951584f887dd25f54c035979f117333319ca/checks?check_suite_id=391052256)

I cannot figure out why we get the error...

**Comment by peaceiris** [comment]
`cargo install mdbook` also failed. [Log](https://github.com/peaceiris/test-NuroDev-atlas/commit/42c7479cbaa801ce12a7c7215e44fe3bae363ece/checks?check_suite_id=391089254)

**Comment by peaceiris** [comment]
I have created a new repository, new mdBook project using `mdbook init` and set up a workflow using this action. All steps have passed.

https://github.com/peaceiris/test-mdbook-2/commit/fec51b8f8f679c6b174cdad0bd507e21e8c1ca49/checks

**Comment by NuroDev** [comment]
Ah okay, after some testing myself it looks like the issue is because the summary file name is case sensitive.
Changing my file from `summary.md` to `SUMMARY.md` fixed the error 🤦‍♂

**Comment by peaceiris** [comment]
I got it.

My local machine macOS is formated with case-insensitive mode, so local building have passed and remote building failed...

**Comment by shreyasminocha** [comment]
Just created rust-lang/mdBook#1240

**Comment by TriplEight** [comment]
I'm experiencing the same but I do not even have any kind of `SUMMARY.md` in the current branch.

**Comment by nathaneastwood** [comment]
I am experiencing this same error.

```
Run mdbook test
Error: -13 07:13:09 [ERROR] (mdbook::utils): Error: Couldn't open SUMMARY.md in "/home/runner/work/fablore/fablore/src" directory
Error: -13 07:13:09 [ERROR] (mdbook::utils): 	Caused By: No such file or directory (os error 2)
Error: Process completed with exit code 101.
```

However I have a `src/SUMMARY.md` file, you can see it's right [here](https://github.com/nathaneastwood/fablore/blob/main/src/SUMMARY.md).

**Comment by VladMasarik** [comment]
@nathaneastwood I am not sure if this will help you, but in my case it was a misconfiguration error because I was missing the `book.tolm` file, and the `-d .` flag. Here is my somewhat shortened code:
```
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Generate Book
        run: |
          cat <<'EOF' > ./SUMMARY.md
          # Summary
          - [Readme](README.md)
          - [Config](CONFIG.md)
          - [Group accounts](GROUPS.md)
          EOF

      - name: Build Book
        run: mdbook build -d .

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          cname: xxx.com
```
Also, your `book.toml` looks almost identical to mine, except I have `src = "."`
