### ISSUE TITLE
proposal: Allow use with additional backends

### ISSUE THREAD

**Issue by JoshOrndorff** [peaceiris/actions-mdbook#95]
**Is your feature request related to a problem? Please describe.**
I link to use [mdbook-linkcheck](https://github.com/Michael-F-Bryan/mdbook-linkcheck) to check links in my text. I haven't been able to get it working with this action.

**Describe the solution you'd like**
I'd like a feature where I can specify what additional backends I'm using and have them installed.

**Describe alternatives you've considered**
One alternative is to not use this action, and instead do something more manual as described in the [mdbook-linkcheck readme](https://github.com/Michael-F-Bryan/mdbook-linkcheck#continuous-integration)

**Additional context**
My repo is https://github.com/substrate-developer-hub/recipes/

**Comment by peaceiris** [comment]
Did you try the following?

```yaml
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.3.5'

      - name: Install mdbook-linkcheck
        run: |
          curl -LSfs https://japaric.github.io/trust/install.sh | \
            sh -s -- --git Michael-F-Bryan/mdbook-linkcheck

      - run: mdbook build
```
